version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: demon-app
    container_name: skyes
    restart: unless-stopped
    env_file: .env
    environment:
      - PORT=$PORT
    ports:
      - "3000:3000"
    networks:
      - app-network

  mongodb:
    image: mongo
    container_name: monggo
    restart: unless-stopped
    networks:
      - app-network

  redis:
    image: redis:6.2
    container_name: readis
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
